<?php

/**
 * This is the model base class for the table "gcm_users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GCMUsers".
 *
 * Columns in table "gcm_users" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $reg_id
 *
 */
abstract class BaseGCMUsers extends CActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gcm_users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GCMUsers|GCMUsers', $n);
	}

	public static function representingColumn() {
		return 'reg_id';
	}

	public function rules() {
		return array(
			array('reg_id', 'required'),
			array('reg_id', 'length', 'max'=>250),
			array('id, reg_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'reg_id' => Yii::t('app', 'Reg'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('reg_id', $this->reg_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}